btrfs-progs: check: lowmem, fix false alerts about EXTENT_OWNER
[BUG]
When simple quota is enabled, lowmem will give false alerts:

  [3/8] checking extents
  ERROR: extent[13631488 168 1048576] has unknown ref type: 172
  ERROR: extent[63963136 168 131072] has unknown ref type: 172
  ERROR: extent[63963136 168 131072] has unknown ref type: 172
  ERROR: file extent[257 0] root 256 owner 256 backref lost
  ERROR: extent[13631488 168 1048576] has unknown ref type: 172
  ERROR: file extent[258 0] root 256 owner 256 backref lost
  ERROR: errors found in extent allocation tree or chunk allocation

[CAUSE]
Lowmem mode has strict checks on the inlined backref type, and
unfortunately EXTENT_OWNER_REF is not inside the support 4 backref types,
thus it's treated as an unknown type, and caused the false alerts.

[FIX]
Add the EXTENT_OWNER_REF type into the supported types.

For lowmem check itself, those key types are just skipped as it's only
to indicate the owner of a data extent, which will be verified by qgroup
part.

Pull-request: #1113
Signed-off-by: Qu Wenruo <wqu@suse.com>
Signed-off-by: David Sterba <dsterba@suse.com>